version: '3.8'
services:
  smarcare:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smarcare
    image: smarcare:0.0.26
    depends_on:
      - orion
    environment:
      - ORION_SERVER_URL=http://orion:1026

  orion:
    image: fiware/orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo

  mongo:
    image: mongo:4.4
    command: --nojournal

  draco:
    image: ging/fiware-draco:2.1.0
    container_name: draco
    environment:
      - NIFI_WEB_HTTPS_PORT=9090
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=pass1234567890
    ports:
      - "9090:9090"
      - "5050:5050"

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0833509162Aa
    ports:
      - 3306:3306
